### ISSUE TITLE
Possibly switch libmd recipe to the freedesktop.org one

### ISSUE THREAD

**Issue by guillemj** [gobolinux/Recipes#4]
Hi!

I've noticed that due to the new dpkg update (thanks for that!), a libmd recipe was added. I'd suggest switching it to use the one announced in https://lists.freedesktop.org/archives/ftp-release/2016-February/000700.html, which has more liberal licenses (no BSD-4-clause), and has up-to-date message digest functions, compatibility with more BSDs, a pkg-config file, etc.

**Comment by hishamhm** [comment]
@guillemj Thank you for the heads-up! And sorry for taking a long time to respond. We weren't checking the github issue trackers! I clicked on "watch" to be notified of new stuff now.

@lucasvr since you uploaded this recipe, can you check this?

**Comment by guillemj** [comment]
@hishamhm Thanks, and no problem!

**Comment by Barrocas** [comment]
@lucasvr is somewhat busy (also my fault), so I made the new recipe, it compiled fine in Gobo-016-beta, I uploaded it, for your final check up before approval.

Also notice that as we already have the previous  version 0.3 on the store, any user trying to compile LibMD will be directed to 0.3 instead of 0.0.0
