### ISSUE TITLE
Fix any and all broken recipes

### ISSUE THREAD

**Issue by BeatLink** [gobolinux/Recipes#57]

**Comment by lucasvr** [comment]
If you want to help on this one, please take a look at the https://github.com/gobolinux/DevelScripts/blob/master/bin/RecipeHealth script. It may need small changes so it becomes aware of the git repository at /Data/Compile/Recipes but otherwise it should be a good starting point.

Note that finding broken recipes is really hard, as that depends on the compiler version used and the installed dependencies, to name just two. That's more of a constant review effort (for which we really need volunteers) rather than an issue that we can track and fix for good. Please open a ticket on specific tools or recipes and, if possible, send us PRs so we can improve the codebase.
