### ISSUE TITLE
Deny Recipes for Core Software, with only gobolinux maintainers having the ability to add them

### ISSUE THREAD

**Issue by RohanOne** [gobolinux/Recipes#7]

**Comment by lucasvr** [comment]
I don't understand what's being requested here. Can you elaborate more?

**Comment by RohanOne** [comment]
Recently i tried updating gcc to the latest version and the last time i compiled it it didnt work. Maybe it would be best to prevent just anyone from sending in new recipees for core software like linux or shadow since its so easy to break the system completely

**Comment by hishamhm** [comment]
All recipes go through approved GoboLinux commiters. Sending a recipe via
ContributeRecipe does not automatically put it in the recipe store.

This of course does not guarantee that all recipes are bug-free. :)
Sometimes a working recipe breaks because another dependency was uploaded.

**Comment by RohanOne** [comment]
Oh okay

**Comment by RohanOne** [comment]
Do the developers try to run through a freshen session for errors? Because im trying to update the system but there are always some recipes that wont compile

**Comment by RohanOne** [comment]
Also where can i submit a bug for the gobolinux 16 beta? X keeps crashing when i installed it in virtualbox

**Comment by hishamhm** [comment]
> Do the developers try to run through a freshen session for errors?

No, but corrections and updates to recipes are always welcome!

> Also where can i submit a bug for the gobolinux 16 beta? 

If it's about the LiveCD environment, you can use https://github.com/gobolinux/LiveCD/issues

> X keeps crashing when i installed it in virtualbox

Are you getting "no screens found"? I ran into this as well, but couldn't solve it yet. You can work around it like this:

1. run `X -configure`, this will generate `xorg.conf.new`
2. edit `xorg.conf.new` and replace `"fbdev"` by `"vesa"`
3. start X with `startx -- -config ./xorg.conf.new`

This will start X in a low resolution (1024x768, I think), but should be enough to get into graphical mode from VirtualBox. As far as I can tell, this issue is specific with VirtualBox, and won't happen if you use the system in an actual machine using different drivers, or if you install it to a VirtualBox HD and then compile the VirtualBox guest additions for your specific VirtualBox version, to get their specific video driver (haven't tested it myself, though, but it should work).

**Comment by hishamhm** [comment]
As for this specific entry, I'm closing it since the question has been addressed.
