### ISSUE TITLE
Recipe error wifi-radar

### ISSUE THREAD

**Issue by WilsonRU** [gobolinux/Recipes#8]
There is an error in the WiFi-radar recipe he can not find the url "download.berlios.de"

"Error fetching archive (s)."

**Comment by hishamhm** [comment]
On Nov 16, 2016 11:45 AM, "Wilson Moura" <notifications@github.com> wrote:
>
> There is an error in the WiFi-radar recipe he can not find the url "
download.berlios.de"
>
> "Error fetching archive (s)."

This means the developers of the package moved the file, probably because
the program was updated. You can try to find the URL to the .tar.gz (or
.tar.bz2, or .tar.xz...) file of the new version online in their web page,
then type `NewVersion wifi-radar <version-number> <url-for-tar.gz>`.

Then run `Compile wifi-radar` again. If it works, run `ContributeRecipe
wifi-radar` to send it for inclusion in the repository. It is this easy to
become a GoboLinux contributor! :)

**Comment by Barrocas** [comment]
I'd also like to point that the current Gobo016-beta version (testing)
already has a good working wifi, so those aditional programs may even not
be necessary. Of course, having other available program options is 'nice to
have'.

In Gobo015 wifi wasn't working properly, at least for me.

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by WilsonRU** [comment]
@hishamhm Error send recipe

xterm > "Failed packing /Data/Compile/PackedRecipes/Wifi-Radar--2.0-r2--recipe.tar.bz2."
xterm > "Recipe failed validation. Not submitting"

**Comment by WilsonRU** [comment]
@hishamhm 

wilson@gnu ~] sudo ContributeRecipe Wifi-Radar 2.0-r2
Failed packing /Data/Compile/PackedRecipes/Wifi-Radar--2.0-r2--recipe.tar.bz2.
Recipe failed validation. Not submitting.

This is all the output I get in the terminal

**Comment by hishamhm** [comment]
please post the contents of the file /Data/Compile/LocalRecipes/Wifi-Radar/2.0/Recipe here (I think that is the correct path). You can use https://gist.github.com to publish the file and then share the link here.

**Comment by Barrocas** [comment]
Hi,
I made a NewVersion of the recipe, with updated source and links, and uploaded it, it's waiting approval, because it installs on Gobo-016-Beta, but it's still not working properly, running the command I get this:

hugo@EeePC ~]wifi-radar
Traceback (most recent call last):
  File "/usr/bin/wifi-radar", line 39, in <module>
    import gtk
ImportError: No module named gtk

Also, is the /Resources/Tasks file still necessary?

**Comment by hishamhm** [comment]
Thanks for contributing, but please avoid uploading recipes when you know
they are not working. We don't test-run the submitted  programs ourselves
(we only look for problems evident from looking at the Recipe diff), so
when I see a recipe in the review queue I assume the uploader considered it
ready for inclusion.

(Yes, that's a low bar for entry but it's what we can afford right now.)

**Comment by hishamhm** [comment]
As for the "import gtk" error, the program is probably missing PyGtk and
friends in its dependencies? (Or some path is not properly set somewhere)

**Comment by Barrocas** [comment]
I understand, but I uploaded this one so you or others can view/check/modify.

**Comment by hishamhm** [comment]
I understood that :) What I meant to say is that the checking that goes in
the review queue doesn't catch this kind of things. I'm managing the queue
mostly by myself, and I'm unable to debug unfinished recipes. I'm barely
keeping up with email nowadays! :)

**Comment by Barrocas** [comment]
I can imagine... :)

I'm trying to help, updating any recipe I can, and testing it on
Gobo-016-Beta, but keep on bumping on errors or fails that most times
I cannot understand enough to know how to properly correct :P

Learning as we go... and these days it's been go,go,go!!!

That's why I immediately warn about defective uploaded recipes ;)

I have no other way of uploading a defective recipe for somebody else
to review, or how can I flag it as needing to be worked somehow?

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by Barrocas** [comment]
Python and PyGTK 2.24.0 are installed.
Dependencies are satisfied. 

Maybe it need Polkit?

**Comment by hishamhm** [comment]
If PyGTK is installed and "import gtk" is failing with "no module named
gtk", it's definitely a path issue (in Python or PyGTK), with a possible
mismatch in Python versions (lib/python2.x with different x).

I don't remember if we still set PYTHONPATH (typing this from the phone on
the bus), but I think the path configuration is in a config file somewhere
in /Programs/Python. The Python recipe might have a clue.

**Comment by lucasvr** [comment]
I see that the most recent version of the recipe is working. I'm closing this ticket now.
